# A service that provides a static URL for gitRepo type kubernetes volues
apiVersion: v1
kind: Service
metadata:
  name: git
  namespace: git
spec:
  ports:
  - targetPort: 3000
    port: 80
    name: http
  type: ClusterIP
  selector:
    app: gogs
