apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: persistent
  namespace: git
spec:
  serviceName: persistent
  replicas: 1
  template:
    metadata:
      labels:
        app: git
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
        ]'
    spec:
      containers:
      - name: git-httpd
        image: local/yolean/git-httpd
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: datadir
          mountPath: /opt/git
  volumeClaimTemplates:
  - metadata:
      name: datadir
      namespace: git
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
