apiVersion: apps/v1alpha1
kind: PetSet
metadata:
  name: gogs
  namespace: git
spec:
  serviceName: gogs
  replicas: 1
  template:
    metadata:
      labels:
        app: gogs
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
        pod.alpha.kubernetes.io/init-containers: '[
        ]'
    spec:
      containers:
      - name: gogs
        image: gogs/gogs
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: datadir
          mountPath: /data
        env:
        - name: SOCAT_LINK
          value: "false"
  volumeClaimTemplates:
  - metadata:
      name: datadir
      namespace: git
      annotations:
        volume.alpha.kubernetes.io/storage-class: anything
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 100Mi
