apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: drone
    component: server
spec:
  selector:
    app: drone
    component: server
  ports:
    - name: http
      port: 80
      protocol: TCP
  # for local testing
  type: NodePort
