apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: drone
    component: server
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  # temporarily, for local testing only
  type: NodePort
