apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cluster-perimeter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cluster-perimeter
    spec:
      containers:
        - name: proxy
          image: httpd:2.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/apache2/conf
      volumes:
        - name: config-volume
          configMap:
            name: proxy-conf
